{% set name = "distoptica" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/distoptica-{{ version }}.tar.gz
  sha256: a4aa46b57cb158d4631a657755261cbc45f07c1c922c9d1ed76acf7e6d96c1c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - fancytypes >=1.0.0
    - pytorch

test:
  imports:
    - distoptica
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/distoptica/
  summary: Python library for modelling optical distortions.
  dev_url: https://github.com/mrfitzpa/distoptica
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
